---

shell: /bin/bash
az_path: /usr/local/bin/

provider_list:
- Microsoft.RedHatOpenShift
- Microsoft.Storage
- Microsoft.Compute
- Microsoft.Authorization

feature_list: []

subnet_list:
- name: 'master-subnet'
  aro_type: 'master'
- name: 'worker-subnet'
  aro_type: 'worker'

apiserver_visibility: Public
ingress_visibility: Public

# Minimum worker count is 3
worker_count: 3
worker_vm_size: 'Standard_D4s_v3'
worker_vm_disk_size_gb: 128
master_vm_size: 'Standard_D8s_v3'
service_cidr: 172.30.0.0/16
pod_cidr: 10.128.0.0/14
wait: no

# The following parameters are used to check for cluster creation status.
retry_delay: 120
retry_count: 30

# The following parameters are used to pause for subnet provisioning
subnet_delay: 30
subnet_retries: 2
